[package]
name = "file_renamer"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
chrono = "0.4.41"
clap = { version = "4.5.38", features = ["derive"] }
regex = "1.11.1"
tempfile = "3.3"
walkdir = "2.3"

[dev-dependencies]
tempfile = "3.3"
